### PR TITLE
Add support for non-ldap groups

### PR DESCRIPTION
**Pull request by neeravkumar**

### CODE REVIEW

**Comment by fabiofenoglio** [comment]
Thank you for your contribution @neeravkumar, I'm not quite fond about untyping groups and exposing a raw `interface{}` to be honest so I would also consider an alternative solution.

> Groups can be a list of strings when using a non-ldap idp

is this behavior described in cloudflare documentation? Can you point me to the docs page or to how you reproduced the issue?

**Comment by neeravkumar** [comment]
I can't find the docs but how I reproduced it was with okta as idp I get:

```
time="2022-12-05T16:33:41Z" level=info msg="---redacted---"
```

I have redacted my email and ip address.

This is with:

```
--- a/vendor/github.com/fabiofenoglio/gin-cloudflare-access/cloudflare_client.go
+++ b/vendor/github.com/fabiofenoglio/gin-cloudflare-access/cloudflare_client.go
@@ -4,11 +4,11 @@ import (
        "context"
        "errors"
        "fmt"
-       "net/http"
-       "time"
-
        "github.com/coreos/go-oidc/v3/oidc"
        resty "github.com/go-resty/resty/v2"
+       log "github.com/sirupsen/logrus"
+       "net/http"
+       "time"
 )
 
 const (
@@ -188,6 +188,8 @@ func (s *cloudflareAccessClientImpl) fetchIdentity(ctx context.Context, raw stri
                return nil, fmt.Errorf("got HTTP server error reading user groups: %v %v", resp.StatusCode(), resp.Status())
        }
 
+       log.Info(resp.String())
+
```

You can also see: https://community.cloudflare.com/t/how-to-know-which-users-are-in-which-groups/146807/5
where they also see different formats based on different IDPs.

I also agree that doing this with interfaces is ugly so I am open to a better solution if you can think of one.

**Comment by fabiofenoglio** [comment]
thank you for the additional information @neeravkumar, this is indeed a difficult situation. 
Please check this proposed solution: https://github.com/fabiofenoglio/gin-cloudflare-access/pull/4

**Comment by neeravkumar** [comment]
Thanks for such a fast response and your solution indeed looks better! I will close this.

**Comment by fabiofenoglio** [comment]
tag [v0.2.4](https://github.com/fabiofenoglio/gin-cloudflare-access/releases/tag/v0.2.4) was deployed with a solution for the issue

**Pull request closed without merging**
